language: node_js
node_js: 12.14.1
cache: yarn

env:
  - CI=false

jobs:
  include:
    - stage: install
      script: yarn install

    - stage: lint
      script: yarn run lint

    - stage: tests
      script: yarn run test

    - stage: build
      script: yarn run build

    - stage: deploy
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
        edge: true
        on:
          branch: master
