language: node_js
node_js: 12.14.1
cache: yarn

env:
  - CI=false

jobs:
  include:
    - stage: install
      script: yarn install

    - stage: lint
      script: yarn run lint

    - stage: tests
      script: yarn run test

    - stage: build
      script: yarn run build

    - stage: deploy
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        local-dir: build
        keep-history: true
        edge: true
        on:
          all_branches: true
#      if: (type = push AND branch = master)
#      github_token: $GITHUB_TOKEN
#      username: $USER_NAME
#      password: $PASS
#      script: yarn run deploy
