export const FETCH_RECIPES_PENDING = 'recipes/FETCH_RECIPES_PENDING';
export const FETCH_RECIPES_SUCCESS = 'recipes/FETCH_RECIPES_SUCCESS';
export const FETCH_RECIPES_ERROR = 'recipes/FETCH_RECIPES_ERROR';

export const ADD_RECIPE_PENDING = 'recipes/ADD_RECIPE_PENDING';
export const ADD_RECIPE_SUCCESS = 'recipes/ADD_RECIPE_SUCCESS';
export const ADD_RECIPE_ERROR = 'recipes/ADD_RECIPE_ERROR';

export const UPDATE_RECIPE_PENDING = 'recipes/UPDATE_RECIPE_PENDING';
export const UPDATE_RECIPE_SUCCESS = 'recipes/UPDATE_RECIPE_SUCCESS';
export const UPDATE_RECIPE_ERROR = 'recipes/UPDATE_RECIPE_ERROR';

export const DELETE_RECIPE_PENDING = 'recipes/DELETE_RECIPE_PENDING';
export const DELETE_RECIPE_SUCCESS = 'recipes/DELETE_RECIPE_SUCCESS';
export const DELETE_RECIPE_ERROR = 'recipes/DELETE_RECIPE_ERROR';

export const SET_SELECTED_RECIPE = 'recipes/SET_SELECTED_RECIPE';

export const SET_CONTENT_VISIBLE = 'recipes/SET_CONTENT_VISIBLE';

export const SET_EDIT_MODE = 'recipes/SET_EDIT_MODE';

export const SET_ACTIVE_PAGE = 'recipes/SET_ACTIVE_PAGE';

export const SET_DELETE_DIALOG_IS_VISIBLE = 'recipes/SET_DELETE_DIALOG_IS_VISIBLE';

export const CLEAR = 'recipes/CLEAR';
