export const SET_ERROR_MESSAGE = 'app/SET_ERROR_MESSAGE';
export const CLEAR_ERROR_MESSAGE = 'app/CLEAR_ERROR_MESSAGE';

export const SET_INFO_MESSAGE = 'app/SET_INFO_MESSAGE';
export const CLEAR_INFO_MESSAGE = 'app/CLEAR_INFO_MESSAGE';

export const SET_SUCCESS_MESSAGE = 'app/SET_SUCCESS_MESSAGE';
export const CLEAR_SUCCESS_MESSAGE = 'app/CLEAR_SUCCESS_MESSAGE';
