export const FETCH_CATEGORIES_PENDING = 'categories/FETCH_CATEGORIES_PENDING';
export const FETCH_CATEGORIES_SUCCESS = 'categories/FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_ERROR = 'categories/FETCH_CATEGORIES_ERROR';

export const ADD_CATEGORY_PENDING = 'categories/ADD_CATEGORY_PENDING';
export const ADD_CATEGORY_SUCCESS = 'categories/ADD_CATEGORY_SUCCESS';
export const ADD_CATEGORY_ERROR = 'categories/ADD_CATEGORY_ERROR';

export const UPDATE_CATEGORY_PENDING = 'categories/UPDATE_CATEGORY_PENDING';
export const UPDATE_CATEGORY_SUCCESS = 'categories/UPDATE_CATEGORY_SUCCESS';
export const UPDATE_CATEGORY_ERROR = 'categories/UPDATE_CATEGORY_ERROR';

export const DELETE_CATEGORY_PENDING = 'categories/DELETE_CATEGORY_PENDING';
export const DELETE_CATEGORY_SUCCESS = 'categories/DELETE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_ERROR = 'categories/DELETE_CATEGORY_ERROR';

export const SET_CATEGORY_PHOTO = 'categories/SET_CATEGORY_PHOTO';

export const CLEAR = 'categories/CLEAR';
